contact_links:
  - name: 💡 Feature Request or Enhancement
    url: ../../discussions/categories/feature-requests
    about: Suggest new features or improvements
  - name: 💬 Questions & Ideas Discussion
    url: ../../discussions
    about: Ask questions and discuss ideas
  - name: 🎮 Discord Community Chat
    url: https://discord.gg/HXHzYvNrfV
    about: Ask quick questions or chat on the Next Friday community Discord server
