name: Environment Setup
description: Sets up Node.js environment with pnpm and installs dependencies

inputs:
  node-version:
    description: Node.js version to use
    required: false
    default: "20"
  git-email:
    description: Git email to use for commits
    required: false
    default: "github-actions[bot]@users.noreply.github.com"
  git-name:
    description: Git name to use for commits
    required: false
    default: "github-actions[bot]"

runs:
  using: composite
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10.12.1

    - name: Setup Node.js with pnpm cache
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: "pnpm"

    - name: Setup Git User
      shell: bash
      run: |
        git config --global user.email "${{ inputs.git-email }}"
        git config --global user.name "${{ inputs.git-name }}"

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
