name: Stale Issue Management

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"

defaults:
  run:
    shell: bash

permissions:
  issues: write
  pull-requests: write
  actions: write

jobs:
  manage-stale-issues:
    name: Close Stale Issues and PRs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        name: Close stale issues
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          close-issue-message: >
            This issue has been automatically closed due to inactivity.
            If you believe this was closed by mistake, please feel free to reopen it or leave a comment.
            Thank you for your understanding.

            _Note: This is an automated message._
          days-before-issue-close: 7
          days-before-issue-stale: 30
          stale-pr-label: stale
          stale-issue-label: stale
          days-before-pr-close: 7
          days-before-pr-stale: 15
          only-pr-labels: "postpone: more info or changes requested, please add a reproduction"
          exempt-issue-labels: roadmap,feature,bug
          operations-per-run: 200
